function [scenario, egoVehicle] = driving_scenario_500m_DLC()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.7 (R2019b) and Automated Driving Toolbox 3.0 (R2019b).
% Generated on: 10-Dec-2020 01:39:24

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 -0.2 0;
    500 -0.1 0];
laneSpecification = lanespec(2, 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [1 -3 0.01]);
waypoints = [1 -3 0.01;
    10 -3 0;
    20 -3 0;
    30 -3 0;
    40 -3 0;
    50 -3 0;
    60 -3 0;
    70 -2.9 0;
    80 -2.2 0;
    90 0.5 0;
    100 0.5 0;
    110 0.5 0;
    120 0.5 0;
    130 -2.2 0;
    140 -2.9 0;
    150 -3 0;
    160 -3 0;
    170 -3 0;
    180 -3 0;
    190 -2 0;
    200 0 0;
    210 2 0;
    220 3 0;
    230 3 0;
    240 3 0;
    250 3 0;
    260 3 0;
    270 3 0;
    280 3 0;
    290 3 0;
    300 3 0;
    310 2 0;
    320 1 0;
    330 0 0;
    340 0 0;
    350 0 0;
    360 0 0;
    370 0 0;
    380 0 0;
    390 0 0;
    400 0 0;
    410 0 0];
speed = 10;
trajectory(egoVehicle, waypoints, speed);

ref_sig = [];
magOffset = 3;
while advance(scenario)
    ref_sig = [ref_sig;  [scenario.SimulationTime, egoVehicle.Position(2)+magOffset, egoVehicle.Yaw ]];
end
plot(ref_sig(:,1), ref_sig(:,2), ref_sig(:,1), ref_sig(:,3));
ref_sig_500m_DLC_ts = timeseries( [ref_sig(:,2), ref_sig(:,3)], ref_sig(:,1) );
save('ref_sig_500m_DLC_ts.mat', 'ref_sig_500m_DLC_ts');

